8.out: 8.c
	gcc 8.c -I/usr/local/include -L/usr/local/lib -lwiringPi -o 8.out

7.out: 7.c
	gcc 7.c -I/usr/local/include -L/usr/local/lib -lwiringPi -o 7.out

6.out: 6.c
	gcc 6.c -I/usr/local/include -L/usr/local/lib -lwiringPi -o 6.out