/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hamster.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
hmstr_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		hmstr_rpc_new_req hmstr_new_1_arg;
		hmstr_rpc_lookup_req hmstr_lookup_1_arg;
		hmstr_rpc_directory_req hmstr_directory_1_arg;
		hmstr_rpc_howsdoing_req hmstr_howsdoing_1_arg;
		hmstr_rpc_readentry_req hmstr_readentry_1_arg;
		hmstr_rpc_givetreats_req hmstr_givetreats_1_arg;
		hmstr_rpc_collect_req hmstr_collect_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case HMSTR_NEW:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_new_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_new_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_new_1_svc;
		break;

	case HMSTR_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_lookup_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_lookup_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_lookup_1_svc;
		break;

	case HMSTR_DIRECTORY:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_directory_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_directory_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_directory_1_svc;
		break;

	case HMSTR_HOWSDOING:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_howsdoing_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_howsdoing_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_howsdoing_1_svc;
		break;

	case HMSTR_READENTRY:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_readentry_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_readentry_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_readentry_1_svc;
		break;

	case HMSTR_GIVETREATS:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_givetreats_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_givetreats_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_givetreats_1_svc;
		break;

	case HMSTR_COLLECT:
		_xdr_argument = (xdrproc_t) xdr_hmstr_rpc_collect_req;
		_xdr_result = (xdrproc_t) xdr_hmstr_rpc_collect_resp;
		local = (char *(*)(char *, struct svc_req *)) hmstr_collect_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (HMSTR_PROG, HMSTR_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, HMSTR_PROG, HMSTR_VERS, hmstr_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (HMSTR_PROG, HMSTR_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, HMSTR_PROG, HMSTR_VERS, hmstr_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (HMSTR_PROG, HMSTR_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
