/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 6.5 */
/* Thu Mar 26 01:12:32 2020 */

/* parameterized module instance */
dpram __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), .RdClock( ), 
    .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
